### ISSUE TITLE
Collaboration on DynamoDB client

### ISSUE THREAD

**Issue by michaelwittwer** [trevorhanus/dynaflo#2]
Hi there

I just found your library which has some pretty similar functionality to our own library which just got a major rewrite in version 5.x.x.
Maybe you are interested in some collaboration work, here is the link to check it out: https://github.com/shiftcode/dynamo-easy.

Or maybe you are just looking for a client which has some new features like transactions. Would love to hear what you think.

**Comment by trevorhanus** [comment]
Hey @michaelwittwer- Just checked out dynamo-easy, looks really cool. I like the fluent api (obviously, since that was what I was doing here). Also really like the idea of being able to define models. Have you seen [https://github.com/baseprime/dynamodb](https://github.com/baseprime/dynamodb)? They also allow you to define models and they use @hapi/joi to do some validation, which I thought was pretty cool. Although, I thought the rest of their module was lacking.

I'd definitely be interested in some collaboration. Let me know what you would be looking for.

I was thinking about pulling out the piece of this library that actually creates the params object that is sent to AWS and have that as a separate module. That way others who may not want the model piece or the client, could use it to more easily create a params object for requests to AWS's dynamo client.
